import React, { useMemo } from 'react';
import { motion } from 'framer-motion';
import clsx from 'clsx';
import { ResponsiveContainer, AreaChart, Area, XAxis, YAxis, Tooltip } from 'recharts';
import Icon from '@/components/ui/Icon';

const formatCOP = (v) => v == null ? '' : new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(v);

export default function StoreDashboard({ 
  metrics, 
  storeEnabled, 
  setStoreEnabled, 
  invoices, 
  setActiveTab,
  storeSlug,
  activeTab = 'dashboard'
}) {
  
  // Public URL
  const publicUrl = `${import.meta.env.VITE_STORE_PUBLIC_URL || 'https://gestivaone-store.vercel.app'}/${storeSlug || ''}`;

  // Compute total revenue generated by store & best month
  const { totalRevenue, bestMonth } = useMemo(() => {
    let total = 0;
    const monthMap = {};
    
    invoices.forEach(inv => {
      const amt = Number(inv.total || inv.total_amount || 0);
      total += amt;

      const dateStr = inv.created_at || inv.date;
      if (dateStr) {
        const d = new Date(dateStr);
        const monthKey = d.toLocaleString('es-CO', { month: 'long', year: 'numeric' });
        monthMap[monthKey] = (monthMap[monthKey] || 0) + amt;
      }
    });

    let maxMonth = 'N/A';
    let maxAmount = 0;
    Object.entries(monthMap).forEach(([mKey, mAmt]) => {
      if (mAmt >= maxAmount) {
        maxAmount = mAmt;
        maxMonth = mKey;
      }
    });

    if (maxMonth !== 'N/A') {
      maxMonth = maxMonth.charAt(0).toUpperCase() + maxMonth.slice(1);
    }

    return {
      totalRevenue: total,
      bestMonth: maxMonth !== 'N/A' ? `${maxMonth} (${formatCOP(maxAmount)})` : 'Sin datos'
    };
  }, [invoices]);

  // Compute 7-day order distribution for the Line Chart (Sin background, solo líneas)
  const last7DaysOrders = useMemo(() => {
    const dayLabels = ['Dom', 'Lun', 'Mar', 'Mié', 'Jue', 'Vie', 'Sáb'];
    const today = new Date();
    const result = [];
    
    // Generate last 7 days
    for (let i = 6; i >= 0; i--) {
      const d = new Date();
      d.setDate(today.getDate() - i);
      const dayName = dayLabels[d.getDay()];
      const dateStr = d.toISOString().split('T')[0];
      
      const dayCount = invoices.filter(inv => {
        const invDate = inv.created_at || inv.date;
        return invDate && invDate.startsWith(dateStr);
      }).length;

      result.push({
        day: dayName,
        pedidos: dayCount,
        // Revenue trend curve calculation for smooth visual line
        ingresos: dayCount * 50000,
        isToday: i === 0
      });
    }
    
    return result;
  }, [invoices]);

  return (
    <motion.div 
      initial={{ opacity: 0, y: 15 }} 
      animate={{ opacity: 1, y: 0 }} 
      className="flex flex-col gap-6 w-full pb-6"
    >
      
      {/* ==========================================
          MAIN HERO BENTO GRID (Standby Card)
          ========================================== */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-stretch">
        
        {/* STANDBY HERO CARD */}
        <div className="lg:col-span-12 rounded-2xl bg-gradient-to-br from-purple-900/20 via-brand-500/10 to-indigo-900/20 border border-purple-500/20 p-5 sm:p-9 flex flex-col justify-between relative overflow-hidden min-h-[240px] sm:min-h-[280px]">
          
          {/* Header Label */}
          <div className="flex items-center justify-between z-10">
            <div className="flex items-center gap-2">
              <span className="text-[10px] font-extrabold uppercase tracking-widest text-purple-400">ESTADO DEL CANAL</span>
            </div>
          </div>

          {/* Center Main Message */}
          <div className="my-4 sm:my-6 z-10 max-w-xl">
            <h2 className="text-3xl sm:text-5xl font-black text-foreground dark:text-white tracking-tight mb-2">
              {storeEnabled ? 'Tienda Activa.' : 'Standby.'}
            </h2>
            <p className="text-xs sm:text-sm text-muted-400 font-medium leading-relaxed">
              {storeEnabled 
                ? 'Tu tienda virtual está recibiendo pedidos contra entrega en tiempo real.' 
                : 'El catálogo está oculto. Usa el interruptor para publicar el sistema.'}
            </p>
          </div>

          {/* Action Button & Live Preview Link */}
          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-2.5 sm:gap-3 z-10">
            <button
              onClick={() => setStoreEnabled(!storeEnabled)}
              className={clsx(
                "px-5 sm:px-6 py-3 sm:py-3.5 rounded-2xl text-xs font-black uppercase tracking-wider transition-all duration-300 flex items-center justify-center gap-2 cursor-pointer transform active:scale-95",
                storeEnabled
                  ? "bg-rose-500 hover:bg-rose-600 text-white"
                  : "bg-brand-500 hover:bg-brand-600 text-white"
              )}
            >
              <Icon name={storeEnabled ? "EyeOff" : "Sparkles"} size={16} />
              <span>{storeEnabled ? 'Pausar tienda' : 'Publicar tienda'}</span>
            </button>

            {storeSlug && (
              <a
                href={publicUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="px-5 py-3 sm:py-3.5 rounded-2xl bg-surface-800/80 hover:bg-surface-700 border border-subtle text-foreground dark:text-white text-xs font-bold transition-all flex items-center justify-center gap-2"
              >
                <span>Ver preview</span>
                <Icon name="ExternalLink" size={13} className="text-muted-400" />
              </a>
            )}
          </div>

          {/* Right 3D Vector Graphic */}
          <div className="absolute right-6 top-1/2 -translate-y-1/2 pointer-events-none hidden md:block opacity-90 transform translate-x-2">
            <div className="relative w-60 h-60 flex items-center justify-center">
              <div className="w-52 h-40 rounded-2xl bg-gradient-to-br from-brand-500/20 via-purple-600/30 to-indigo-500/20 border border-purple-400/30 flex flex-col justify-between p-4 backdrop-blur-md transform rotate-2">
                <div className="flex items-center justify-between border-b border-purple-400/20 pb-2">
                  <div className="flex gap-1.5">
                    <span className="w-2.5 h-2.5 rounded-full bg-purple-400/50" />
                    <span className="w-2.5 h-2.5 rounded-full bg-purple-400/30" />
                    <span className="w-2.5 h-2.5 rounded-full bg-purple-400/20" />
                  </div>
                  <div className="text-[10px] font-bold text-purple-300">Storefront</div>
                </div>
                <div className="flex items-center justify-center my-auto">
                  <div className="w-14 h-14 rounded-2xl bg-purple-500/20 border border-purple-400/40 flex items-center justify-center text-purple-300">
                    <Icon name={storeEnabled ? "Store" : "EyeOff"} size={28} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* ==========================================
            LOG DE PEDIDOS BANNER (Sin background en el gráfico, integrado a la card)
            ========================================== */}
        <div className="lg:col-span-12 rounded-2xl bg-slate-950 border border-slate-800 text-white p-5 sm:p-7 flex flex-col md:flex-row md:items-center justify-between gap-6 sm:gap-8 relative overflow-hidden">
          
          {/* Left Info Column */}
          <div className="flex flex-col justify-center min-w-[200px] gap-2.5 sm:gap-3 shrink-0">
            <div className="flex items-center gap-2 text-purple-400">
              <Icon name="Activity" size={16} />
              <span className="text-[10px] font-extrabold uppercase tracking-widest">LOG DE PEDIDOS</span>
            </div>

            {/* Pedidos Totales */}
            <div>
              <div className="text-3xl sm:text-4xl font-black tracking-tight text-white">{invoices.length}</div>
              <div className="text-xs text-slate-400 font-medium">Pedidos Totales</div>
            </div>

            <div className="w-full h-px bg-slate-800/80 my-0.5" />

            {/* Total Generado por la Tienda */}
            <div>
              <div className="text-[10px] font-extrabold text-slate-400 uppercase tracking-wider">TOTAL GENERADO</div>
              <div className="text-xl sm:text-2xl font-black text-emerald-400 tracking-tight">{formatCOP(totalRevenue)}</div>
            </div>

            {/* Mejor Mes */}
            <div>
              <div className="text-[10px] font-extrabold text-slate-400 uppercase tracking-wider">MEJOR MES</div>
              <div className="text-xs font-bold text-purple-300 mt-0.5">{bestMonth}</div>
            </div>
          </div>

          {/* CENTER / RIGHT GRAPHIC (Gráfico de Líneas estilo Imagen 2 - Sin background, integrado a la card) */}
          <div className="flex-1 w-full flex flex-col justify-between min-h-[180px] sm:min-h-[190px]">
            <div className="flex flex-wrap items-center justify-between gap-2 mb-3 border-b border-slate-800/50 pb-2">
              <div className="flex items-center gap-2">
                <Icon name="TrendingUp" size={16} className="text-purple-400" />
                <span className="text-xs font-bold text-slate-200">Actividad de Pedidos (Últimos 7 días)</span>
              </div>
              <div className="flex items-center gap-3 text-[10px] font-bold">
                <span className="flex items-center gap-1 text-purple-400">
                  <span className="w-2 h-2 rounded-full bg-purple-500" />
                  Pedidos
                </span>
                <span className="flex items-center gap-1 text-emerald-400">
                  <span className="w-2 h-2 rounded-full bg-emerald-400" />
                  Sincronizado
                </span>
              </div>
            </div>

            {/* Recharts Area/Line Chart directly rendered on card background */}
            <div className="w-full h-40">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={last7DaysOrders} margin={{ top: 10, right: 10, left: -25, bottom: 0 }}>
                  <defs>
                    <linearGradient id="purpleAreaGrad" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#A855F7" stopOpacity={0.35}/>
                      <stop offset="95%" stopColor="#A855F7" stopOpacity={0.0}/>
                    </linearGradient>
                    <linearGradient id="emeraldAreaGrad" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#34D399" stopOpacity={0.25}/>
                      <stop offset="95%" stopColor="#34D399" stopOpacity={0.0}/>
                    </linearGradient>
                  </defs>
                  
                  <XAxis 
                    dataKey="day" 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fill: '#94A3B8', fontSize: 11, fontWeight: 700 }} 
                  />
                  <YAxis 
                    axisLine={false} 
                    tickLine={false} 
                    tick={{ fill: '#64748B', fontSize: 10 }} 
                    allowDecimals={false}
                  />
                  <Tooltip 
                    contentStyle={{ 
                      backgroundColor: '#0F172A', 
                      borderColor: '#334155', 
                      borderRadius: '12px', 
                      color: '#F8FAFC',
                      fontSize: '12px',
                      fontWeight: 'bold',
                      boxShadow: 'none'
                    }}
                    formatter={(val, name) => [name === 'pedidos' ? `${val} pedidos` : formatCOP(val), name === 'pedidos' ? 'Pedidos' : 'Tendencia']}
                  />
                  
                  {/* Secondary Line Curve (Emerald) */}
                  <Area 
                    type="monotone" 
                    dataKey="ingresos" 
                    stroke="#34D399" 
                    strokeWidth={2} 
                    fillOpacity={1} 
                    fill="url(#emeraldAreaGrad)" 
                    dot={false}
                  />

                  {/* Primary Line Curve (Purple Gestiva) */}
                  <Area 
                    type="monotone" 
                    dataKey="pedidos" 
                    stroke="#A855F7" 
                    strokeWidth={3} 
                    fillOpacity={1} 
                    fill="url(#purpleAreaGrad)" 
                    dot={{ r: 4, fill: '#A855F7', stroke: '#0F172A', strokeWidth: 2 }}
                    activeDot={{ r: 6, fill: '#34D399', stroke: '#FFFFFF', strokeWidth: 2 }}
                  />
                </AreaChart>
              </ResponsiveContainer>
            </div>
          </div>

        </div>

      </div>

    </motion.div>
  );
}
