import React from 'react';
import {
  Activity,
  AlertCircle,
  TriangleAlert,
  AlignCenter,
  AlignLeft,
  AlignRight,
  Archive,
  ArrowDown,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Award,
  BarChart3,
  Barcode,
  Banknote,
  Bell,
  BookOpen,
  Bookmark,
  Box,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  Camera,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clipboard,
  Clock,
  Cloud,
  Coins,
  Columns,
  Contact,
  Cookie,
  Copy,
  Cpu,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Download,
  Edit,
  Edit2,
  Edit3,
  ExternalLink,
  Eye,
  EyeOff,
  FileCheck,
  FilePlus,
  FileSpreadsheet,
  FileText,
  FileUp,
  Filter,
  Folder,
  FolderClosed,
  FolderPlus,
  Gem,
  Globe,
  GripVertical,
  Hash,
  HelpCircle,
  History,
  Home,
  Image as ImageIcon,
  ImagePlus,
  Info,
  Inbox,
  Key,
  Landmark,
  Languages,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Link2,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize2,
  Menu,
  MessageCircle,
  MessageSquare,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  MoreVertical,
  MousePointerClick,
  Package,
  PackagePlus,
  Palette,
  Paperclip,
  PartyPopper,
  Pen,
  Percent,
  Phone,
  Plane,
  PlugZap,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  RotateCw,
  Save,
  ScanLine,
  Search,
  Send,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Star,
  Store,
  Sun,
  Tag,
  ThermometerSun,
  Trash,
  Trash2,
  TrendingUp,
  Truck,
  Type,
  Unlock,
  Upload,
  User,
  UserCheck,
  UserPlus,
  Users,
  Users2,
  Utensils,
  Wallet,
  Wifi,
  WifiOff,
  Wrench,
  X as CloseIcon,
  Zap,
  ZapOff
} from 'lucide-react';

// Pure JS React SVG Component for Facebook
const Facebook = ({ size = 24, color = "currentColor", ...props }) =>
  React.createElement('svg', {
    width: size,
    height: size,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: color,
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    ...props
  },
    React.createElement('path', { d: "M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" })
  );

// Pure JS React SVG Component for Instagram
const Instagram = ({ size = 24, color = "currentColor", ...props }) =>
  React.createElement('svg', {
    width: size,
    height: size,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: color,
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    ...props
  },
    React.createElement('rect', { width: 20, height: 20, x: 2, y: 2, rx: 5, ry: 5 }),
    React.createElement('path', { d: "M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" }),
    React.createElement('line', { x1: 17.5, x2: 17.51, y1: 6.5, y2: 6.5 })
  );

// Pure JS React SVG Component for Youtube
const Youtube = ({ size = 24, color = "currentColor", ...props }) =>
  React.createElement('svg', {
    width: size,
    height: size,
    viewBox: "0 0 24 24",
    fill: "none",
    stroke: color,
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    ...props
  },
    React.createElement('path', { d: "M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.56 49.56 0 0 1-16.2 0A2 2 0 0 1 2.5 17" }),
    React.createElement('polygon', { points: "10 15 15 12 10 9 10 15" })
  );

export const icons = {
  // Common alias keys
  home: Home,
  search: Search,
  settings: Settings,
  dashboard: LayoutDashboard,
  user: User,
  inventory: Package,
  cart: ShoppingCart,
  receipt: Receipt,
  analytics: BarChart3,
  notification: Bell,
  menu: Menu,
  close: CloseIcon,
  x: CloseIcon,

  // Direct Lucide PascalCase & camelCase mapping for 100% project-wide compatibility
  Activity, activity: Activity,
  AlertCircle, alertCircle: AlertCircle,
  AlertTriangle: TriangleAlert, alertTriangle: TriangleAlert,
  AlignCenter, alignCenter: AlignCenter,
  AlignLeft, alignLeft: AlignLeft,
  AlignRight, alignRight: AlignRight,
  Archive, archive: Archive,
  ArrowDown, arrowDown: ArrowDown,
  ArrowDownRight, arrowDownRight: ArrowDownRight,
  ArrowLeft, arrowLeft: ArrowLeft,
  ArrowRight, arrowRight: ArrowRight,
  ArrowUp, arrowUp: ArrowUp,
  ArrowUpRight, arrowUpRight: ArrowUpRight,
  Award, award: Award,
  BarChart3, barChart3: BarChart3, barChart: BarChart3,
  Barcode, barcode: Barcode,
  Banknote, banknote: Banknote,
  Bell, bell: Bell,
  BookOpen, bookOpen: BookOpen,
  Bookmark, bookmark: Bookmark,
  Box, box: Box,
  Briefcase, briefcase: Briefcase,
  Building, building: Building,
  Building2, building2: Building2,
  Calculator, calculator: Calculator,
  Calendar, calendar: Calendar,
  CalendarDays, calendarDays: CalendarDays,
  Camera, camera: Camera,
  Check, check: Check,
  CheckCircle, checkCircle: CheckCircle,
  CheckCircle2, checkCircle2: CheckCircle2,
  ChevronDown, chevronDown: ChevronDown,
  ChevronLeft, chevronLeft: ChevronLeft,
  ChevronRight, chevronRight: ChevronRight,
  ChevronUp, chevronUp: ChevronUp,
  Clipboard, clipboard: Clipboard,
  Clock, clock: Clock,
  Cloud, cloud: Cloud,
  Coins, coins: Coins,
  Columns, columns: Columns,
  Contact, contact: Contact,
  Cookie, cookie: Cookie,
  Copy, copy: Copy,
  Cpu, cpu: Cpu,
  CreditCard, creditCard: CreditCard,
  Crown, crown: Crown,
  Database, database: Database,
  DollarSign, dollarSign: DollarSign,
  Download, download: Download,
  Edit, edit: Edit,
  Edit2, edit2: Edit2,
  Edit3, edit3: Edit3,
  ExternalLink, externalLink: ExternalLink,
  Eye, eye: Eye,
  EyeOff, eyeOff: EyeOff,
  Facebook, facebook: Facebook,
  FileCheck, fileCheck: FileCheck,
  FilePlus, filePlus: FilePlus,
  FileSpreadsheet, fileSpreadsheet: FileSpreadsheet,
  FileText, fileText: FileText,
  FileUp, fileUp: FileUp,
  Filter, filter: Filter,
  Folder, folder: Folder,
  FolderClosed, folderClosed: FolderClosed,
  FolderPlus, folderPlus: FolderPlus,
  Gem, gem: Gem,
  Globe, globe: Globe,
  GripVertical, gripVertical: GripVertical,
  Hash, hash: Hash,
  HelpCircle, helpCircle: HelpCircle,
  History, history: History,
  Home, home: Home,
  Image: ImageIcon, image: ImageIcon,
  ImagePlus, imagePlus: ImagePlus,
  Inbox, inbox: Inbox,
  Info, info: Info,
  Instagram, instagram: Instagram,
  Key, key: Key,
  Landmark, landmark: Landmark,
  Languages, languages: Languages,
  Layers, layers: Layers,
  LayoutDashboard, layoutDashboard: LayoutDashboard,
  LayoutGrid, layoutGrid: LayoutGrid,
  Link, link: Link,
  Link2, link2: Link2,
  Loader2, loader2: Loader2,
  Lock, lock: Lock,
  LogOut, logOut: LogOut,
  Mail, mail: Mail,
  MapPin, mapPin: MapPin,
  Maximize2, maximize2: Maximize2,
  Menu, menu: Menu,
  MessageCircle, messageCircle: MessageCircle,
  MessageSquare, messageSquare: MessageSquare,
  Minimize2, minimize2: Minimize2,
  Minus, minus: Minus,
  Monitor, monitor: Monitor,
  Moon, moon: Moon,
  MoreVertical, moreVertical: MoreVertical,
  MousePointerClick, mousePointerClick: MousePointerClick,
  Package, package: Package,
  PackagePlus, packagePlus: PackagePlus,
  Palette, palette: Palette,
  Paperclip, paperclip: Paperclip,
  PartyPopper, partyPopper: PartyPopper,
  Pen, pen: Pen,
  Percent, percent: Percent,
  Phone, phone: Phone,
  Plane, plane: Plane,
  PlugZap, plugZap: PlugZap,
  Plus, plus: Plus,
  Printer, printer: Printer,
  Receipt, receipt: Receipt,
  RefreshCw, refreshCw: RefreshCw,
  RotateCw, rotateCw: RotateCw,
  Save, save: Save,
  ScanLine, scanLine: ScanLine,
  Search, search: Search,
  Send, send: Send,
  Server, server: Server,
  Settings, settings: Settings,
  Shield, shield: Shield,
  ShieldAlert, shieldAlert: ShieldAlert,
  ShieldCheck, shieldCheck: ShieldCheck,
  ShoppingBag, shoppingBag: ShoppingBag,
  ShoppingCart, shoppingCart: ShoppingCart,
  SlidersHorizontal, slidersHorizontal: SlidersHorizontal,
  Smartphone, smartphone: Smartphone,
  Smile, smile: Smile,
  Snowflake, snowflake: Snowflake,
  Sparkles, sparkles: Sparkles,
  Star, star: Star,
  Store, store: Store,
  Sun, sun: Sun,
  Tag, tag: Tag,
  ThermometerSun, thermometerSun: ThermometerSun,
  Trash, trash: Trash,
  Trash2, trash2: Trash2,
  TrendingUp, trendingUp: TrendingUp,
  Truck, truck: Truck,
  Type, type: Type,
  Unlock, unlock: Unlock,
  Upload, upload: Upload,
  User, user: User,
  UserCheck, userCheck: UserCheck,
  UserPlus, userPlus: UserPlus,
  Users, users: Users,
  Users2, users2: Users2,
  Utensils, utensils: Utensils,
  Wallet, wallet: Wallet,
  Wifi, wifi: Wifi,
  WifiOff, wifiOff: WifiOff,
  Wrench, wrench: Wrench,
  X: CloseIcon, x: CloseIcon,
  Youtube, youtube: Youtube,
  Zap, zap: Zap,
  ZapOff, zapOff: ZapOff
};
